FROM mitodl/ol-infrastructure@sha256:514166a9e059c4f36325a6280448780e285a2d237108c66f889f72656598018b as infra

FROM python:3.11-slim@sha256:6d2502238109c929569ae99355e28890c438cb11bc88ef02cd189c173b3db07c
ENV PYTHONUNBUFFERED=1
ARG PACKER_VERSION=1.10.3
WORKDIR /opt/resource

RUN apt-get update -yqq && apt-get install -yqq curl jq openssh-client unzip && \
    curl "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip" -o packer.zip && \
    unzip packer.zip -d /bin/ && \
    rm -f packer.zip &&\
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    packer plugins install github.com/hashicorp/amazon
COPY bin/* /opt/resource/
COPY lib/* /opt/resource/lib/

ENV PATH /bin:/usr/bin/:/usr/local/bin:/home/app/.local/bin:/home/app/workspace/.venv/bin/
COPY --from=infra /usr/local/ /usr/local/
CMD ["/bin/sh"]
