FROM mitodl/ol-infrastructure@sha256:01f927a34104e94e69d9e66b4e4fedceda61a9e2eb853663f6f731072cbe1957 as infra

FROM python:3.11-slim@sha256:fc39d2e68b554c3f0a5cb8a776280c0b3d73b4c04b83dbade835e2a171ca27ef
ENV PYTHONUNBUFFERED=1
ARG PACKER_VERSION=1.10.3
WORKDIR /opt/resource

RUN apt-get update -yqq && apt-get install -yqq curl jq openssh-client unzip && \
    curl "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip" -o packer.zip && \
    unzip packer.zip -d /bin/ && \
    rm -f packer.zip &&\
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    packer plugins install github.com/hashicorp/amazon && \
    packer plugins install github.com/hashicorp/docker
COPY bin/* /opt/resource/
COPY lib/* /opt/resource/lib/

ENV PATH /bin:/usr/bin/:/usr/local/bin:/home/app/.local/bin:/home/app/workspace/.venv/bin/
COPY --from=infra /usr/local/ /usr/local/
CMD ["/bin/sh"]
