---
resource_types:
- name: packer
  type: docker-image
  source:
    repository: mitodl/concourse-packer-resource
    tag: latest

resources:
- icon: github
  name: packer_templates
  source:
    branch: main
    paths:
    - src/bilder/images/
    uri: https://github.com/mitodl/ol-infrastructure
  type: git
- name: validate-template-dir
  type: packer

jobs:
- name: validate-template-dirs
  plan:
  - get: packer_templates
    trigger: true
  - in_parallel:
    - put: validate-template-dir
      params:
        template: packer_templates/src/bilder/images/concourse/.
    - put: validate-template-dir
      params:
        template: packer_templates/src/bilder/images/consul/.
    - put: validate-template-dir
      params:
        template: packer_templates/src/bilder/images/edxapp/.
    - put: validate-template-dir
      params:
        template: packer_templates/src/bilder/images/vault/.
