---
resource_types:
- name: packer
  type: docker-image
  source:
    repository: mitodl/concourse-packer-resource
    tag: latest

resources:
- icon: github
  name: packer_templates
  source:
    branch: main
    paths:
    - src/bilder/images/
    uri: https://github.com/mitodl/ol-infrastructure
  type: git
- name: artifact-build-schedule
  type: time
  icon: clock-outline
  source:
    start: 0400
    stop: 0500
    days: [Sunday]
- name: execute-packer
  type: packer

jobs:
- name: packer-validate-workflow
  plan:
  - get: packer_templates
    trigger: true
  - in_parallel:
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/concourse/.
        objective: validate
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/consul/.
        objective: validate
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/edxapp/.
        objective: validate
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/vault/.
        objective: validate
- name: packer-build-workflow
  plan:
  - get: artifact-build-schedule
    trigger: true
  - get: packer_templates
    trigger: false
  - in_parallel:
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/concourse/.
        objective: build
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/consul/.
        objective: build
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/edxapp/.
        objective: build
    - put: execute-packer
      params:
        template: packer_templates/src/bilder/images/vault/.
        objective: build
